### ISSUE TITLE
 Nextcloud doesn't sync files reliably from Mac client: internal server error

### ISSUE THREAD

**Issue by sebastian-ruiz** [evertramos/docker-nextcloud-letsencrypt#1]
The Mac client gives an internal server error after syncing a few files. 
`...php_network_getaddresses: getaddrinfo failed...` appears in the docker log

Nextcloud is working great in the browser and I my contacts and calendars are syncing fine.

More information on the issue here: nextcloud/server#9624

**Comment by evertramos** [comment]
Did you set on the webproxy the realip.conf? Are you using cloudflare?

**Comment by evertramos** [comment]
As it seems you are having issue to connect to the Database Container... 

Did you try to remove the different port of your cloud-db: 

```
ports:
      - "3308:3306"
```

and try it over...

And in that `cloud-app` you do not need to specify the `ports` option neither the `VIRTUAL_PORT`, in that case, ok?

**Comment by sebastian-ruiz** [comment]
As per https://github.com/evertramos/docker-nextcloud-letsencrypt/issues/1#issuecomment-392799531 I removed the extra options I added to the `docker-compose.yml` and restored it to the one in the repository. I still get the internal server error in the client.

Answering https://github.com/evertramos/docker-nextcloud-letsencrypt/issues/1#issuecomment-392770520 : For the letsencrypt-nginx-proxy, in the file `data/conf.d/realip.conf` I have `set_real_ip_from  172.19.0.0/16;` which is the IPAM subnet of the `webproxy` network. I don't use cloudflare so I left those lines in `realip.conf` commented out. I still get an in internal server error in the nextcloud client.

In `.env` I have 

```
NGINX_WEB=nginx-web
DOCKER_GEN=nginx-gen
LETS_ENCRYPT=nginx-letsencrypt

IP=0.0.0.0
NETWORK=webproxy
NGINX_FILES_PATH=./data
USE_NGINX_CONF_FILES=true
```
Using my real external ip address instead of `0.0.0.0` gives the error `driver failed programming external connectivity` so I left it as is.

**Comment by evertramos** [comment]
So, it works on the Browser but it does not work on the Mac? Is that it? It seems as your comment on nextcloud repo that is a db connection issue... So, none should be working... please confirm

**Comment by sebastian-ruiz** [comment]
Yes it works fine in my browser, I can view my files and I can edit them.
Also, I can connect via webdav https with Transmit and here I can also read and write files.

It is only the Mac client which gives `server replied: Internal Server Error` when I try and sync files.

**Comment by evertramos** [comment]
@vephinx I have test it here with Windows Client and it worked just fine uploaded 5Gb of data some pictures with 8Mb and some iso with 500Mb, so the issue might be on the Mac client for some reason... I don´t think is an issue related to this repo.

**Comment by evertramos** [comment]
Just to make sure that we have a issue on the mac client please test my own enrironment sent to your email. Wait your reply.

**Comment by evertramos** [comment]
Server will be running for the next 24 hour...

**Comment by evertramos** [comment]
Since we do not have any reply from you we will close this issue.

**Comment by sebastian-ruiz** [comment]
Hi sorry, I have been busy and I missed your email. I have run some tests, all resulting in the same problem:

1. I ran the client on windows - same problem
2. I ran `docker-compose down`, deleted the data folder, ran `docker-compose up -d` - same problem
2. Instead of running on `cloud.example.com` I tried `nextcloud.example.com` - same problem

I found out what does work, but it is definitely suboptimal, namely I commented out 
```
LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
```
leaving this line
```
VIRTUAL_HOST: ${VIRTUAL_HOST}
```
which as expected runs the instance on `http://cloud.example.com` and this does not trigger the `server replied: Internal Server Error` in the client. I would also like to note that before attempting to run nextcloud on docker, I had nextcloud running natively, with nginx and letsencrypt also running natively on Ubuntu 16.04 and I did not have this problem.

I have noticed that if I connect to the `cloud.example.com` instance via webdav with Transmit, then transmit may try and connect to `differentsubdomain.example.com`, at least that is what littlesnitch tells me (I have multiple subdomains pointed to the same ip and in future I would like to use the `docker-compose-letsencrypt-nginx-proxy-companion` to run docker instances on a few subdomains). Maybe this is a similar problem to https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/69 ?

I reason that it therefore may have something to do with the `docker-compose-letsencrypt-nginx-proxy-companion` not properly routing the subdomain, although I do not have enough evidence to fully support this. Maybe every now and again nextcloud client is trying to connect to `differentsubdomain.example.com` which then causes the error.

**Comment by sebastian-ruiz** [comment]
For now I use this temporary solution. I disabled `docker-compose-letsencrypt-nginx-proxy-companion` and used my local nginx with the following basic configuration:

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name cloud.example.com;
    # enforce https
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name  cloud.example.com;

    ssl_certificate /etc/letsencrypt/live/cloud.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cloud.example.com/privkey.pem;

    client_max_body_size 512M;

    location / {
        proxy_pass http://172.19.0.8:80;
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-for $remote_addr;
        port_in_redirect off;
        proxy_connect_timeout 300;
    }
}
```
I will investigate what part of the `docker-compose-letsencrypt-nginx-proxy-companion`, `data/conf.d/default.conf` is causing the problem.
