### ISSUE TITLE
Error to connect database

### ISSUE THREAD

**Issue by ghost** [evertramos/docker-nextcloud-letsencrypt#10]
Hi Evert,
Actually, i install a new server with docker.
I use your work :)
docker-compose-Nginx-Letsencryt is ok
docker-portainer-letsencrypt is ok
But for docker-nextcloud-letsencrypt , i have a problem.
When i start a new installation of nextcloud, i have : 
`Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused`

I Don't understand because my .env is totaly similar of my docker-nextcloud-letsencrypt. I just change : 

> Host 
> VIRTUAL_HOST=_cloud.yourdomain.com_
> LETSENCRYPT_HOST=_cloud.yourdomain.com_
> LETSENCRYPT_EMAIL=_your_email@yourdomain.com_

and i change 

> Nextcloud local data path
> LOCAL_DB_DIR=/home/user/cloud/data/db
> LOCAL_DATA_DIR=/home/user/cloud/data/cloud
> LOCAL_CONF_DIR=/home/user/cloud/data/cloud/config
> LOCAL_APPS_DIR=/home/user/cloud/data/cloud/apps

By

> Nextcloud local data path
> LOCAL_DB_DIR=./data/db
> LOCAL_DATA_DIR=./data/cloud
> LOCAL_CONF_DIR=./data/cloud/config
> LOCAL_APPS_DIR=./data/cloud/apps

Thank a lot for your reply

Christophe

**Comment by ghost** [comment]
Hi,

I Don't understand, because now, is ok. I close this issue.


Best regards,

Christophe

**Comment by evertramos** [comment]
I read this issue and noticed that it has nothing to do with the variables only with database connection... glad it´s working!
