### ISSUE TITLE
Urgent security issue in NGINX/php-fpm

### ISSUE THREAD

**Issue by ghost** [evertramos/docker-nextcloud-letsencrypt#11]
Hi Evert,

Can you put this patch in place which seems urgent?

https://nextcloud.com/blog/urgent-security-issue-in-nginx-php-fpm/

Thank a lot :)

Tof

**Comment by evertramos** [comment]
Hello @Tofdu31!

Thanks for you concern. This patch is meant to be updated inside the nextcloud container, so I suggest backing up and start the environment with the latest version of the Nextcloud container, as it seems is being updated recently.

https://hub.docker.com/_/nextcloud?tab=tags

**Comment by ghost** [comment]
Ok Thanks 👍
