### ISSUE TITLE
collabora office inside this configuration

### ISSUE THREAD

**Issue by mariomare22** [evertramos/docker-nextcloud-letsencrypt#14]
Hey, do you have any idea on how to install Collabora without impacting current (perfect) configuration?

Thanks

**Comment by mariomare22** [comment]
found a way, launching occ command inside cloud-app container. thanks.

**Comment by evertramos** [comment]
@mariomare22 sorry to miss that... but you could use command or even better create your dockerfile... cheers!

glad you solved.
