### ISSUE TITLE
Nextcloud proxy settings

### ISSUE THREAD

**Issue by brasofilo** [evertramos/docker-nextcloud-letsencrypt#17]
Hi Evert, first of all thanks a lot for this repo, after much trying examples around, yours worked at first try, great stuff, thanks a bunch!

I'm having some upload issues and tried lots of things (nginx .conf settings, stopping server antivirus, php settings) but I'm still unable to upload files bigger than 1M...

I just read that adjusting NC proxy settings could be a good thing, do you think it's necessary? I think `overwritehost`  and `overwriteprotocol` would be the relevant ones, but I'm not sure what to use for `overwritehost`...
https://github.com/nextcloud/server/blob/master/config/config.sample.php#L451

**Comment by evertramos** [comment]
It's probably the nextcloud settings... 

But, please check your proxy:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/conf.d/uploadsize.conf

And your nextcloud http settings for max upload.

**Comment by brasofilo** [comment]
I think I found it: `/nextcloud/config/php/php-local.ini`, I added the following:
```nginx
memory_limit = 2048M
upload_max_filesize = 2048M
post_max_size = 2048M
```

Terminei usando os containers da [linuxserver.io](https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/), achei bem mais simples 
E estava fuçando o Traefik que parece super pro mas agora mesmo é demaiszão pra mim :)
