### ISSUE TITLE
Windows / Linux client : “Connection Closed”

### ISSUE THREAD

**Issue by ghost** [evertramos/docker-nextcloud-letsencrypt#2]
Hi,

Thank you very much for your nice work

I installed without problem the docker-compose-letsencrypt-nginx-proxy-companion and then installed and docker-nextcloud-letsencrypt.

I did not encounter any particular problem on the server side. Some settings in the Cpanel of Nextcloud and it's perfect!

I'm just enabled PHP-FPM on the domain in CPanel .But in Nextcloud Client (Linux and Windows) i have : Connection closed after a few minutes of synchronization

I have about 95GB of sync to do. So I settled in the Cpanel at 110 GB to be quiet

Despite having stopped the container Nextcloud and DB, always the same error

The error is the same with the Nextcloud client as the Owncloud client

Do you have an idea ? Thank you very much Ramos

**Comment by evertramos** [comment]
Hello @Tofdu31,

Thanks for your message!

Have you tried disabling the fpm? Do you get the same error?

I am not sure why this is happening... I have sync way more files than that, and no errors...

I believe it might be the fpm configuration which our webproxy is not realy refined... I have seen some updates on the script for fpm, which was updated in our script as well, but did not test it all in production. So, if you please, disable the fpm, try it again and let me know. 

If it works... I would suggest (and if you want could send a PR) add a new nginx for the fpm to this repo, so it would be independt fromt he proxy.... just a suggestion as well.

Wait your comments.

**Comment by ghost** [comment]
Hi,
Exactly, I do not know where to go to disable the fpm ...

**Comment by evertramos** [comment]
In the cpanel you mentioned that you enabled.. right? can you disable it?

**Comment by ghost** [comment]
Rereading my post, I actually wanted to say that I changed the size. The cpanel is in French because I'm french :)
![capture_nextcloud_bug_php-fpm](https://user-images.githubusercontent.com/22862175/47316653-f23e6e80-d647-11e8-9574-a08525462ab9.png)

**Comment by ghost** [comment]
hi, 
Well, I finally understood what's going on.
In the CPANEL, if you write the value in GB, it does not work, although there is no error when you click on save. You must write the value absolutely in MB.

At least for the next ones who do the same stupidity as me ... They will have here the solution ...;)

By cons now, I have the error message in Nextcloud: server replied: server entity too large

In conf.d / uploadsize.conf I change the value client_max_body_size 100m;
  per client_max_body_size 1000m;

Unfortunately, I still have the error message. On the other hand, the Nextcloud client synchronizes without worry.

How can I find a solution to no longer have the error: client_max_body_size 1000m;

Thanks again.

**Comment by ghost** [comment]
60/5000
I open a new issue for client_max_body_size error
