### ISSUE TITLE
SMTP Service for nextcloud

### ISSUE THREAD

**Issue by lutzmarkwirth** [evertramos/docker-nextcloud-letsencrypt#20]
Hi,

first of all many thanks for your great work. I'm a newbie to server administration, the console and all these things. With your files provided life is so much easier... :)

I've noticed that I'm unable to set up a working SMTP-Service in Nextcloud. The error message is:

Expected response code 220 but got code "421", with message "421 smtp.strato.de : No SMTP service (MBL-B) "

Could it be possible that the SMTP service is blocked by nginx. And if so do you have any idea how to change it?

Many thanks in advance.

Greetings from Berlin
Lutz

**Comment by evertramos** [comment]
Hello @lutzmarkwirth !!

Thanks for your kind words. 

Try to install an SMTP in the NextCloud container. 

```
apt update
apt install -y msmtp
```

**Comment by lutzmarkwirth** [comment]
Hi @evertramos,

I was following your advise and have installed msmtp inside the Nextcloud docker container. Unfortunately it hasn't fixed the problem. So I've tried to mail out of the container directly by using the terminal and got exactly the same error message as  in the Nextcloud menu which fully confused me. Thereupon I've tried the credentials of my Gmail account - and it worked... 😅 So the problem doesn't seem to be the docker installation but my email provider - that is also the provider of my cloud server. I will further investigate if others facing the same problems in this conestellation. Anyway, many thanks for your quick reply and the given hint.

May I ask you another question? What is your recommenadtion to run the cron jobs? Inside the container, by using a new container or through a https://cron-job.org/? I was making my life easy in first place. But it feels like I don't want to depend on another provider.

Greetings from Berlin
Lutz

**Comment by lutzmarkwirth** [comment]
> I will further investigate

I've just received feedback from my email provider, Strato in Germany, that their SMTP server isn't compatible with Nextcloud. it pretty much looks like there is no solution for the problem.

Greetings from Berlin and all the best
Lutz

**Comment by evertramos** [comment]
Hello @lutzmarkwirth!

I quiet don’t get the reason why your service provider blocks external smtp... maybe there is a way around it.

About the cron, I normally install the cron and set the entrypoint script to update the rules in the crontab file, just as we would do in regular Linux installation. Just make sure you set timezone in the container as well.

Let me know how it goes!

Cheers!
