### ISSUE TITLE
How can I update Nextcloud?

### ISSUE THREAD

**Issue by ghost** [evertramos/docker-nextcloud-letsencrypt#24]
I installed nextcloud and everything was fine until I realized that my nextcloud version is `17.0.0.9`.
I tried to use the web based updater but as shown in the image the button for updating does nothing.

![nextcloud2](https://user-images.githubusercontent.com/44995063/104660536-0490a100-56c7-11eb-8fc3-644acd0a4434.png)

It's also interesting that it installed this old version by default although I checked my `.env` file for the `APP_IMAGE_TAG` variable which is set to `latest`.

I don't want to use such an outdated version. How can I update my nextcloud correctly?

**Comment by ghost** [comment]
I am still interested in the answer as this could be helpful for the future but for now I just reinstall nextcloud with the `APP_IMAGE_TAG` set to `20.0.5`.

**Comment by evertramos** [comment]
Hello @devrobinkroeker 

The web update should be working smothly, once the nextcloud is running in a container with all possible access just as a regular web server. Not sure why the container available was set to '#', this is not related to this repo or the infrastructure, but on the nextcloud side as it seems.

**Comment by lutzmarkwirth** [comment]
Good morning from Berlin,

I'm also facing the problem that I'm unable to update Nextcloud over the settings menu. When clicking on "open updater" (such as in the first post of this thread) I'll get re-directed to the files menu.

I've installed Nextcloud 19.0.1 following your great tutorials (many thanks!!!) around two years ago and never touched it as it used to run nice and smoothly. Now I'm having the problem that the Android client claims to be incompatible with the server version. Plus I'm having the "80 GB problem", which doesn't let me sync any more files, even though I'm the admin with unlimited space allocated and the server has 800 GB of space.

I would be very greatful if you could give me any advise of how I could update Nextcloud on my server. Many thanks in advance!

Have a great day
Lutz


![Bildschirmfoto 2022-07-16 um 10 09 53](https://user-images.githubusercontent.com/62263835/179346655-8ab04953-8469-4f4f-acc8-7c25dc30d95e.png)
o

**Comment by lutzmarkwirth** [comment]
> I am still interested in the answer as this could be helpful for the future but for now I just reinstall nextcloud with the `APP_IMAGE_TAG` set to `20.0.5`.

This also finally worked for me... :) I have installed release after the other and have `24.0.3` running now.
