### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by meetmarvin** [evertramos/docker-nextcloud-letsencrypt#25]
I followed the instructions and installed it successfully.

However, I'm getting the error below whenever I'm accessing https://<server-ip> (locally)

**503 Service Temporarily Unavailable**

Is this because the IP address of the server is not public and the letsencrypt cert is failing?

Thank you in advance!

**Comment by evertramos** [comment]
Yes sir.! you must be in a public server with public ip address so letsencrypt can issue a cert.
