### ISSUE TITLE
Windows / Linux client : “server replied: server entity too large”

### ISSUE THREAD

**Issue by ghost** [evertramos/docker-nextcloud-letsencrypt#3]
Hi,

After fixing my php-fpm problem, I now have the error: server replied: server entity too large

Looking more ready and looking on the internet, it appears that you have to change the value client_max_body_size

Searching the docker-compose-letsencrypt-nginx-proxy-companion and docker-nextcloud-letsencrypt-nginx-proxy-companion folder is what I got in response:
```
./docker-compose-letsencrypt-nginx-proxy-companion/conf.d/uploadsize.conf
./docker-nextcloud-letsencrypt/data/cloud/core/doc/admin/installation/nginx.html
```
I change the value for both files: 10G

And I then restart the containers.

I change the value for both files: 10G

And I then restart the containers.
Despite the changes, I still have the error message: server replied: server entity too large

Une idée ? (An idea?)  :)

**Comment by evertramos** [comment]
This message is due the nginx configuration which will be easy to fix it!

Please check your settings on the proxy as of here:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/81

And set the size in Mb > "m" as well, which will be 10000m just to make sure.

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/912a55e64648152e52a24a4039f45e5f4b4fc2e1/conf.d/uploadsize.conf#L7

Hope it helps!

**Comment by ghost** [comment]
Thank you very much Ramos, actually with the links, it's easy to correct.
