### ISSUE TITLE
Access through untrusted domain

### ISSUE THREAD

**Issue by samuelba** [evertramos/docker-nextcloud-letsencrypt#6]
I get this error when I first call the domain defined with `VIRTUAL_HOST` and `LETSENCRYPT_HOST`:

```
**Access through untrusted domain**
Please contact your administrator. If you are an administrator, edit the "trusted_domains" setting in config/config.php like the example in config.sample.php.


Further information how to configure this can be found in the documentation.
```

What did I wrong?

**Comment by evertramos** [comment]
Hello @samuelba 

Where did you get this error?

What is you compose look like? 

Are you using the webproxy?

Did the proxy generated the ssl certificate for you?

Does your url is using the ssl?

What are the logs on nginx-web, nginx-letsencrypt and nextcloud container?

**Comment by samuelba** [comment]
I got the error when I first visited the nextcloud website. The compose was the original from this repo. I use your proxy companion with letsencrypt. 

I guess I solved the issue by manually adding my domain to `trusted_domains` in `cloud/data/cloud/config/config.php`. I don't know if this should have been configured automatically by your docker or not.

**Comment by evertramos** [comment]
Glad you solved.

**Comment by Unclezz** [comment]
Hi @evertramos,

this is still happening.
I had same issue and had to arrange same changes described above by @samuelba

**Comment by tmerten** [comment]
Hi everyone,

I can make a pull request to fix this later but here is a diff that should help to fix this @evertramos . Its only one line and maybe you can quickly add it:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 41a1b01..b1b5bef 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -28,6 +28,7 @@ services:
        NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
        NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR}
        NEXTCLOUD_TABLE_PREFIX: ${NEXTCLOUD_TABLE_PREFIX}
+       NEXTCLOUD_TRUSTED_DOMAINS: ${LETSENCRYPT_HOST}
        VIRTUAL_HOST: ${VIRTUAL_HOST}
        LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
        LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
```

In addition (maybe interesting for the docs) I had to start the `mariadb` container way before the `nextcloud` container to have a smooth setup. Otherwise the nextcloud admin user and the trusted domain settings (above) was sometimes not configured correctly because nextcloud did not wait long enough for the db to be up and running:

```bash
docker-compose up -d cloud-db
# wait until its initialized
docker-compose up -d cloud-app
```

**Comment by evertramos** [comment]
done!
