### ISSUE TITLE
Larger client_max_body_size by default

### ISSUE THREAD

**Issue by GijsVermarien** [evertramos/docker-nextcloud-letsencrypt#7]
For the usage of Nextcloud I encountered the problem that the default client_max_body_size is not large enough, so it needs manual configuration as you shown in this [gist](https://github.com/evertramos/nignx-behind-proxy/blob/master/nignx/conf.d/default.conf#L19) of yours. It would be nice if this could be configured by default somehow, I now have to manually set this for the Nextcloud to work properly with anything above 1MB (which is a lot of files if you use this instead of dropbox). Is there any way to incorporate this in the .env file?

**Comment by cyr1z** [comment]
> For the usage of Nextcloud I encountered the problem that the default client_max_body_size is not large enough, so it needs manual configuration as you shown in this [gist](https://github.com/evertramos/nignx-behind-proxy/blob/master/nignx/conf.d/default.conf#L19) of yours. It would be nice if this could be configured by default somehow, I now have to manually set this for the Nextcloud to work properly with anything above 1MB (which is a lot of files if you use this instead of dropbox). Is there any way to incorporate this in the .env file?

Please tell me exactly how you fixed this problem. My configuration looks completely different. The client_max_body_size parameter is not found anywhere

**Comment by praetorianguards** [comment]
i fix the problem by 
$ client_max_body_size 10G >/root/docker-compose-letsencrypt-nginx-proxy-companion/nginx-data/conf.d/max.conf

**Comment by sasacharle** [comment]
Can you detail the process ? I have the same pb

**Comment by kbarbora** [comment]
just to add to previous answer, the paramenters to be modified are the ones in the proxy (not the nextcloud docker instance), you can refer to the proxy repo issues for my answer or the authors answer

**Comment by MacKarp** [comment]
I have modified `nginx.tmpl`  from proxy. I use this only for nextcloud so if you use proxy for something different then this probably would add max file size for all services (dunno didn't test)
 
https://github.com/evertramos/nginx-proxy-automation/blob/master/nginx.tmpl 
Added in line 254
```
server {
	...
	{{ end }}
	{{ $access_log }}

	client_max_body_size 10G;
	
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location /.well-known/acme-challenge/ {
		...
	}
	...
}
```
and 277
```
server {
	...
	{{ end }}
	{{ $access_log }}

	client_max_body_size 10G;

	{{ if eq $network_tag "internal" }}
	# Only allow traffic from internal clients
	include /etc/nginx/network_internal.conf;
	{{ end }}

	...
}
```
Dunno if its best solution but it works for me :)

**Comment by evertramos** [comment]
Hello there!

You could reach the same result by adding this option in here:

https://github.com/evertramos/nginx-proxy-automation/blob/master/conf.d/uploadsize.conf

And start the nginx-proxy-automation with the option:

```bash
./fresh-start.sh -use-nginx-conf-files  ....
```

As of:

https://github.com/evertramos/nginx-proxy-automation/blob/5b66f76f29a58f2928e6b1092c66869466a11146/bin/localscript/usage-fresh-start.sh#L82

But if you already have the proxy running, you might need to do a few tricks to achieve it first.
