### ISSUE TITLE
SSL certificate is not renewing

### ISSUE THREAD

**Issue by mariomare22** [evertramos/docker-nextcloud-letsencrypt#8]
Hi,

my SSL certificate is not renewing, i have tried to recreate all the stack with no success.

**Comment by evertramos** [comment]
are you using https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion?

please post your issue there....

**Comment by evertramos** [comment]
are you using https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion?

please pot your issue there....

**Comment by mariomare22** [comment]
my bad. i closed port 80
