### ISSUE TITLE
Change .env.sample

### ISSUE THREAD

**Issue by ghost** [evertramos/docker-nextcloud-letsencrypt#9]
Hi,
For your .env.sample, i propose to change this 

> # Nextcloud local data path
> LOCAL_DB_DIR=/home/user/cloud/data/db
> LOCAL_DATA_DIR=/home/user/cloud/data/cloud
> LOCAL_CONF_DIR=/home/user/cloud/data/cloud/config
> LOCAL_APPS_DIR=/home/user/cloud/data/cloud/apps

With

> # Nextcloud local data path
> LOCAL_DB_DIR=./cloud/data/db
> LOCAL_DATA_DIR=./cloud/data/cloud
> LOCAL_CONF_DIR=./cloud/data/cloud/config
> LOCAL_APPS_DIR=./cloud/data/cloud/apps

Best regards,

Christophe

**Comment by Elmit2015** [comment]
I just try to install it. What are the directories meant for?
Is local data path for the user on their computer? And nextcloud data dir on the server?

**Comment by evertramos** [comment]
@Tofdu31 

I think this is a nice way to have it. 

Can you pull request it?

**Comment by ghost** [comment]
It's ok for me, but i don't understand your question :)
👍

**Comment by evertramos** [comment]
I mean you make a pull request to the code on github so I can only merge it.

**Comment by ghost** [comment]
I do not know how to do "pull request"
